### ISSUE TITLE
Add .pre-commit-configuration

### ISSUE THREAD

**Issue by jcorrado76** [danielbeach/tinytimmy#10]
Add a `.pre-commit-config.yaml` file with linting configurations. [Here's](https://github.com/jcorrado76/data-science-cookie-cutter-with-package/blob/main/%7B%7B%20cookiecutter.project_name%20%7D%7D/.pre-commit-config.yaml) an example of some pre-commit configs I like.

**Comment by krishnaduttPanchagnula** [comment]
Can take this up. Any action requirements that want to see in this file?

**Comment by danielbeach** [comment]
@krishnaduttPanchagnula It would be nice to see `ruff` run as a linter and `black` as a formatted for the code. And run the local unit tests with `pytest`.
