### ISSUE TITLE
Add the ability to return a Dataframe as something other than Polars.

### ISSUE THREAD

**Issue by danielbeach** [danielbeach/tinytimmy#6]
All results are returned be default as a Polars dataframe. Add the ability to return other dataframes, say Pandas for example.

**Comment by jcorrado76** [comment]
@danielbeach is this resolved in #16? If so, can we mark this (#6) as closed?

**Comment by danielbeach** [comment]
@jcorrado76 no, but I just pushed a PR myself to make this feature available. https://github.com/danielbeach/tinytimmy/pull/25
