### ISSUE TITLE
Support for dbt-style validation configuration files

### ISSUE THREAD

**Issue by jcorrado76** [danielbeach/tinytimmy#8]
I like how DBT lets you define validations via a YAML file. Great expectations does this too. I think it would be nice to let users provide some sort of YAML configuration of validations to be run. This would also allow users to separate non-critical validations from critical guard rail validations.

**Comment by lordirah** [comment]
I would love to give this a try. Will raise a draft PR soon

**Comment by lordirah** [comment]
# Just posting my draft code thoughts
- We will have a `ConfigParser` that reads yaml file
- We will have to validate whether given test in yaml is valid. For this we will get methods from `DataQuality` and assert
- We will have a dataclass validating the input config structure and create object (This will be helpful when our config grows)
- We now will have a `Runner` class which will be the entry point
- `Runner` will use the `ConfigParser` and dynamically trigger the `TinyTimmy` methods

Sample input yaml
```
Tests:
- name: "null_check"
  id: 1
- name: "distinct_check"
  id: 2
```

How we will trigger
```
r = Runner(conf_path="./tinytimmy/test.yaml", source_type="pandas", dataframe=df)
```

**Comment by lordirah** [comment]
Please provide your thoughts on the above
